logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 80
spring:
  application:
    name: gateway-services2
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      routes:
        - id: service1
          uri: lb://ELASTIC-QUARY-CLIENT
          predicates:
              - Path=/documents/**
              - Header=Authorization, Bearer (.*)
          filters:
              - name: RequestRateLimiter
                args:
                  redis-rate-limiter.replenishRate: 1
                  redis-rate-limiter.burstCapacity: 2
        - id: keycloak
          uri: http://localhost:8080/
          predicates:
            - Path=/auth/**
management:
  endpoints:
    health:
      redis:
        enabled: true
      show-details: always
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    refresh:
      enable: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 30