server:
    port: 8761
spring:
    application:
        name: service-registry
eureka:
    server:
        eviction-interval-timer-in-ms: 1
        response-cache-update-interval-ms: 1
    client:
        fetch-registry: false
        registry-with-eureka: false
    instance:
        hostname: 127.0.0.1