server:
  port: 82
eureka:
  client:
    registry-with-eureka: true
    fetch-registry: true
    enabled: true
    healthcheck:
      enable: true
    service-url:
      default-zone: http://server-registry:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${server.port}
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 2
      lease-expiration-duration-in-seconds: 2
spring:
  application:
    name: elastic-quary-client
elastic-config:
  index-name: twitter-index
  connection-url: http://elastic:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure: INFO
    org.springframework.web.client.RestTemplate: DEBUG